export const products = [
    { id: "1", img: "big-mac.jpg", title: "Big Mac", price: "2" },
    { id: "2", img: "flip-flops.jpg", title: "Flip Flops", price: "3" },
    { id: "3", img: "coca-cola-pack.jpg", title: "Coca-cola Pack", price: "5" },
    { id: "4", img: "movie-ticket.jpg", title: "Movie Ticket", price: "12" },
    { id: "5", img: "book.jpg", title: "Book", price: "15" },
    { id: "6", img: "lobster-dinner.jpg", title: "Lobster Dinner", price: "45" },
    { id: "7", img: "video-game.jpg", title: "Video Game", price: "60" },
    { id: "8", img: "amazon-echo.jpg", title: "Amazon Echo", price: "99" },
    { id: "9", img: "year-of-netflix.jpg", title: "Year of Netflix", price: "100" },
    { id: "10", img: "air-jordans.jpg", title: "Air Jordans", price: "125" },
    { id: "11", img: "airpods.jpg", title: "Airpods", price: "199" },
    { id: "12", img: "gaming-console.jpg", title: "Gaming Console", price: "299" },
    { id: "13", img: "drone.jpg", title: "Drone", price: "350" },
    { id: "14", img: "smartphone.jpg", title: "Smartphone", price: "699" },
    { id: "15", img: "bike.jpg", title: "Bike", price: "800" },
    { id: "16", img: "kitten.jpg", title: "Kitten", price: "1500" },
    { id: "17", img: "puppy.jpg", title: "Puppy", price: "1500" },
    { id: "18", img: "auto-rickshaw.jpg", title: "Auto Rickshaw", price: "2300" },
    { id: "19", img: "horse.jpg", title: "Horse", price: "2500" },
    { id: "20", img: "acre-of-farmland.jpg", title: "Acre of Farmland", price: "3000" },
    { id: "21", img: "designer-handbag.jpg", title: "Designer Handbag", price: "5500" },
    { id: "22", img: "hot-tub.jpg", title: "Hot Tub", price: "6000" },
    { id: "23", img: "luxury-wine.jpg", title: "Luxury Wine", price: "7000" },
    { id: "24", img: "diamond-ring.jpg", title: "Diamond Ring", price: "10000" },
    { id: "25", img: "jet-ski.jpg", title: "Jet Ski", price: "12000" },
    { id: "26", img: "rolex.jpg", title: "Rolex", price: "15000" },
    { id: "27", img: "ford-f-150.jpg", title: "Ford F-150", price: "30000" },
    { id: "28", img: "tesla.jpg", title: "Tesla", price: "75000" },
    { id: "29", img: "monster-truck.jpg", title: "Monster Truck", price: "150000" },
    { id: "30", img: "ferrari.jpg", title: "Ferrari", price: "250000" },
    { id: "31", img: "single-family-home.jpg", title: "Single Family Home", price: "300000" },
    { id: "32", img: "gold-bar.jpg", title: "Gold Bar", price: "700000" },
    { id: "33", img: "mcdonalds-franchise.jpg", title: "McDonalds Franchise", price: "1500000" },
    { id: "34", img: "superbowl-ad.jpg", title: "Superbowl Ad", price: "5250000" },
    { id: "35", img: "yacht.jpg", title: "Yatch", price: "750000" },
    { id: "36", img: "m1-abrams.jpg", title: "M1 Abrams", price: "8000000" },
    { id: "37", img: "formula-1-car.jpg", title: "Formula 1 Car", price: "15000000" },
    { id: "38", img: "apache-helicopter.jpg", title: "Apache Helicopter", price: "31000000" },
    { id: "39", img: "mansion.jpg", title: "Mansion", price: "45000000" },
    { id: "40", img: "make-a-movie.jpg", title: "Make a Movie", price: "100000000" },
    { id: "41", img: "boeing-747.jpg", title: "Boeing 747", price: "148000000" },
    { id: "42", img: "mona-lisa.jpg", title: "Mona Lisa", price: "780000000" },
    { id: "43", img: "skyscraper.jpg", title: "Skyscraper", price: "850000000" },
    { id: "44", img: "cruise-ship.jpg", title: "Cruise Ship", price: "930000000" },
    { id: "45", img: "nba-team.jpg", title: "NBA Team", price: "2120000000" },
]